/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiPublicStaffAvatarPathRouteImport } from './routes/api/public/staff-avatar.$path'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaffAvatarPathRoute =
  ApiPublicStaffAvatarPathRouteImport.update({
    id: '/api/public/staff-avatar/$path',
    path: '/api/public/staff-avatar/$path',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/ranks': typeof RanksRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/api/status': typeof ApiStatusRoute
  '/api/public/staff-avatar/$path': typeof ApiPublicStaffAvatarPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/ranks': typeof RanksRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/api/status': typeof ApiStatusRoute
  '/api/public/staff-avatar/$path': typeof ApiPublicStaffAvatarPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/ranks': typeof RanksRoute
  '/rules': typeof RulesRoute
  '/staff': typeof StaffRoute
  '/api/status': typeof ApiStatusRoute
  '/api/public/staff-avatar/$path': typeof ApiPublicStaffAvatarPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/disclaimer'
    | '/events'
    | '/privacy'
    | '/ranks'
    | '/rules'
    | '/staff'
    | '/api/status'
    | '/api/public/staff-avatar/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/disclaimer'
    | '/events'
    | '/privacy'
    | '/ranks'
    | '/rules'
    | '/staff'
    | '/api/status'
    | '/api/public/staff-avatar/$path'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/disclaimer'
    | '/events'
    | '/privacy'
    | '/ranks'
    | '/rules'
    | '/staff'
    | '/api/status'
    | '/api/public/staff-avatar/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangelogRoute: typeof ChangelogRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EventsRoute: typeof EventsRoute
  PrivacyRoute: typeof PrivacyRoute
  RanksRoute: typeof RanksRoute
  RulesRoute: typeof RulesRoute
  StaffRoute: typeof StaffRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiPublicStaffAvatarPathRoute: typeof ApiPublicStaffAvatarPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-avatar/$path': {
      id: '/api/public/staff-avatar/$path'
      path: '/api/public/staff-avatar/$path'
      fullPath: '/api/public/staff-avatar/$path'
      preLoaderRoute: typeof ApiPublicStaffAvatarPathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangelogRoute: ChangelogRoute,
  DisclaimerRoute: DisclaimerRoute,
  EventsRoute: EventsRoute,
  PrivacyRoute: PrivacyRoute,
  RanksRoute: RanksRoute,
  RulesRoute: RulesRoute,
  StaffRoute: StaffRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiPublicStaffAvatarPathRoute: ApiPublicStaffAvatarPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
